# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Yavuz Tas"
description: Senior Java Developer
footer_title: Yavuz is logging...
footer_description: A bunch of <b>java experience</b> from a <b>java lover</b>

email: hi@yavuztas.dev
#blog logo
logo: "/assets/images/avatar1.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/java-blog-4.jpg"
cover_mobile: "/assets/images/java-blog-4-mobile.jpg"

name: 'Yavuz Tas'
author: 'Yavuz Tas'
author_image: "/assets/images/avatar1.png"

paginate:	5

future: true

url: "https://yavuztas.dev" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@yavuztas'

#fill in disqus shortname to use disqus
disqus: yavuztas-dev

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:
    desc: Follow me on Twitter
    share_desc: Share on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/yavuztas
    desc:   Follow me on Github
    share_url:
    share_title:
    share_link:

  - icon: stack-overflow
    url: https://stackoverflow.com/users/7794994/yavuz-tas
    desc: Follow me on Stackoverflow
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://linkedin.com/in/yavuztas/
    desc:   Follow me on Linkedin
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
